### ISSUE TITLE
Validating contact enrollment to Workflow is failing

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-hubspot#12]
1. Create a hubspot contact first.
2. Enroll the contact by selecting the "Enroll a HubSpot Contact into a Workflow" step.
3. In cmd, type crank cog:step automatoninc/hubspot
4. Select "Check Workflow Enrollment of a HubSpot Contact"
5. Enter the contact's email address and workflow id and observe.

![image](https://user-images.githubusercontent.com/54615569/68369896-4eeac980-0176-11ea-99d7-2d4f13b9c85e.png)

Validation step only:
![image](https://user-images.githubusercontent.com/54615569/68369956-6aee6b00-0176-11ea-8129-74f55bee2690.png)

Actual Result:
Test is failing (regardless if yml or step) when user validates an already existing contact in a workflow.
This issue does not occur when user does the enrollment and validation in just 1 scenario.

Expected Result:
Test should not fail when validating if an already existing contact is enrolled to a workflow.

**Comment by amcpanaligan** [comment]
This is so weird that when you get all the enrolled workflows for the same contact it doesn't fetch any. Maybe related to how workflow works? @iamEAP

**Comment by amcpanaligan** [comment]
![image](https://user-images.githubusercontent.com/10269901/68374698-53b47b00-0180-11ea-9994-afacd9ebe4d4.png)
Could it also be that once the `workflow` is in `completed` state then it won't appear on the contact's enrollment anymore?

**Comment by amcpanaligan** [comment]
Logging the workflows by contact has an empty array. The statement above is highly likely

**Comment by iamEAP** [comment]
Yep, I think you've got it right @amcpanaligan: once a Contact has moved through all steps in a Workflow, and therefore the Contact/Workflow state becomes `completed`, which means they are no longer enrolled in the Workflow.

So technically, this is "works as designed," and it just so happens that we are testing against a workflow that is so short that anything beyond an instantaneous check fails.

However, maybe we can use this as an opportunity to tweak the language of the step somewhat to make it clearer.

@roanlibelo, what do you think about changing the step name and text to read something like...

- **Name**: `Check Current Workflow Enrollment of a HubSpot Contact`
- **Expression**: `the (?<email>.+) hubspot contact should currently be enrolled in workflow (?<workflow>.+)`

**Comment by amcpanaligan** [comment]
^ But when you attempt to `Enroll` the contact to the same `workflow` again it says that it is currently enrolled. Maybe we should change the error message as well depending on the workflow status?

**Comment by amcpanaligan** [comment]
Or maybe just say: `Cannot enroll contact to ..... The workflow might have been completed`

**Comment by roanlibelo** [comment]
This is the error message when you try to enroll same account. 
![image](https://user-images.githubusercontent.com/54615569/68446320-57dfa780-0217-11ea-80c0-9ba96ba2caac.png)

**Comment by iamEAP** [comment]
Ah, yes.  So whether or not a contact can be _re_-enrolled in a Workflow is a configurable option on the Workflow itself.  Sometimes, it may make sense to allow a Contact to go through as many times as necessary, while other times, it may only make sense for a Contact to go through once:

- **Every time example**: Workflow that sends out a series of reminder emails ahead of a subscription expiration every year.
- **Only once example**: Workflow that emails out a promotional coupon with a code for a specific event.

I agree with @roanlibelo: a friendlier error message on the enrollment step for the "only once" case would be ideal.  In fact, the error message that HubSpot provides is actually totally acceptable.  Perhaps we can just update all of the error messages to print `error.message`, rather than (or at least ahead of) the raw JSON of the entire error.

**Comment by amcpanaligan** [comment]
Error messages, and test expressions are changed accordingly to prevent misunderstandings on the test results.
